/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Viewer;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author RadenKun
 */
public class GuiView extends javax.swing.JFrame {

    /**
     * Creates new form GuiView
     */
    public GuiView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jPanelNav = new javax.swing.JPanel();
        jPanel1Nav = new javax.swing.JPanel();
        jPanel2Nav = new javax.swing.JPanel();
        jPanel3Nav = new javax.swing.JPanel();
        jPanel4Nav = new javax.swing.JPanel();
        jpanelLogutNav = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanelMenuU = new javax.swing.JPanel();
        jpanel1U = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2U = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3U = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4U = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jPanelH1 = new javax.swing.JPanel();
        jPanelH2 = new javax.swing.JPanel();
        jPanelH3 = new javax.swing.JPanel();
        jPanelH4 = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jPanelTopKiri = new javax.swing.JPanel();
        jpanelKiriDesk = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpanelKiriRegister = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsernameReg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPasswordReg = new javax.swing.JPasswordField();
        jPanelRegistered = new javax.swing.JPanel();
        jLabelRegistered = new javax.swing.JLabel();
        jPanelTopKanan = new javax.swing.JPanel();
        jLabelButtonExit = new javax.swing.JLabel();
        jPanelFormLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsernameLog = new javax.swing.JTextField();
        jPanelLogin = new javax.swing.JPanel();
        jlabelLogin = new javax.swing.JLabel();
        jPanelRegister = new javax.swing.JPanel();
        jLabelRegister = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPasswordLog = new javax.swing.JPasswordField();
        jPanelWallpaper = new javax.swing.JPanel();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelMenu.setVisible(false);

        jPanelNav.setBackground(new java.awt.Color(44, 62, 80));
        jPanelNav.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1Nav.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1Nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1NavMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1NavLayout = new javax.swing.GroupLayout(jPanel1Nav);
        jPanel1Nav.setLayout(jPanel1NavLayout);
        jPanel1NavLayout.setHorizontalGroup(
            jPanel1NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel1NavLayout.setVerticalGroup(
            jPanel1NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanelNav.add(jPanel1Nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        jPanel2Nav.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2Nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2NavMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2NavLayout = new javax.swing.GroupLayout(jPanel2Nav);
        jPanel2Nav.setLayout(jPanel2NavLayout);
        jPanel2NavLayout.setHorizontalGroup(
            jPanel2NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel2NavLayout.setVerticalGroup(
            jPanel2NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanelNav.add(jPanel2Nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 80, -1));

        jPanel3Nav.setBackground(new java.awt.Color(0, 204, 0));
        jPanel3Nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3NavMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3NavLayout = new javax.swing.GroupLayout(jPanel3Nav);
        jPanel3Nav.setLayout(jPanel3NavLayout);
        jPanel3NavLayout.setHorizontalGroup(
            jPanel3NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel3NavLayout.setVerticalGroup(
            jPanel3NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        jPanelNav.add(jPanel3Nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 80, -1));

        jPanel4Nav.setBackground(new java.awt.Color(153, 0, 153));
        jPanel4Nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4NavMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4NavLayout = new javax.swing.GroupLayout(jPanel4Nav);
        jPanel4Nav.setLayout(jPanel4NavLayout);
        jPanel4NavLayout.setHorizontalGroup(
            jPanel4NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel4NavLayout.setVerticalGroup(
            jPanel4NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanelNav.add(jPanel4Nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 80, 70));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Close Window_48px.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpanelLogutNavLayout = new javax.swing.GroupLayout(jpanelLogutNav);
        jpanelLogutNav.setLayout(jpanelLogutNavLayout);
        jpanelLogutNavLayout.setHorizontalGroup(
            jpanelLogutNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jpanelLogutNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLogutNavLayout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jpanelLogutNavLayout.setVerticalGroup(
            jpanelLogutNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jpanelLogutNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelLogutNavLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanelNav.add(jpanelLogutNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 80, 90));

        jPanelMenu.add(jPanelNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 390));

        jPanelMenuU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel10.setText("MENU 1 : HEADER KU MERAH");

        javax.swing.GroupLayout jpanel1ULayout = new javax.swing.GroupLayout(jpanel1U);
        jpanel1U.setLayout(jpanel1ULayout);
        jpanel1ULayout.setHorizontalGroup(
            jpanel1ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(jpanel1ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1ULayout.createSequentialGroup()
                    .addContainerGap(102, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        jpanel1ULayout.setVerticalGroup(
            jpanel1ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
            .addGroup(jpanel1ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1ULayout.createSequentialGroup()
                    .addContainerGap(84, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(161, Short.MAX_VALUE)))
        );

        jPanelMenuU.add(jpanel1U, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel11.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel11.setText("MENU 2 : HEADER KU KUNING");

        javax.swing.GroupLayout jPanel2ULayout = new javax.swing.GroupLayout(jPanel2U);
        jPanel2U.setLayout(jPanel2ULayout);
        jPanel2ULayout.setHorizontalGroup(
            jPanel2ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(jPanel2ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2ULayout.createSequentialGroup()
                    .addContainerGap(102, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        jPanel2ULayout.setVerticalGroup(
            jPanel2ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
            .addGroup(jPanel2ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2ULayout.createSequentialGroup()
                    .addContainerGap(84, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(161, Short.MAX_VALUE)))
        );

        jPanelMenuU.add(jPanel2U, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel12.setText("MENU 3 : HEADER KU HIJAU");

        javax.swing.GroupLayout jPanel3ULayout = new javax.swing.GroupLayout(jPanel3U);
        jPanel3U.setLayout(jPanel3ULayout);
        jPanel3ULayout.setHorizontalGroup(
            jPanel3ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(jPanel3ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3ULayout.createSequentialGroup()
                    .addContainerGap(102, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        jPanel3ULayout.setVerticalGroup(
            jPanel3ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
            .addGroup(jPanel3ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3ULayout.createSequentialGroup()
                    .addContainerGap(84, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(161, Short.MAX_VALUE)))
        );

        jPanelMenuU.add(jPanel3U, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel13.setText("MENU 4 : HEADER KU UNGU");

        javax.swing.GroupLayout jPanel4ULayout = new javax.swing.GroupLayout(jPanel4U);
        jPanel4U.setLayout(jPanel4ULayout);
        jPanel4ULayout.setHorizontalGroup(
            jPanel4ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(jPanel4ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4ULayout.createSequentialGroup()
                    .addContainerGap(102, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        jPanel4ULayout.setVerticalGroup(
            jPanel4ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
            .addGroup(jPanel4ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4ULayout.createSequentialGroup()
                    .addContainerGap(84, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(161, Short.MAX_VALUE)))
        );

        jPanelMenuU.add(jPanel4U, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelMenu.add(jPanelMenuU, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 89, 700, -1));

        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelH1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanelH1Layout = new javax.swing.GroupLayout(jPanelH1);
        jPanelH1.setLayout(jPanelH1Layout);
        jPanelH1Layout.setHorizontalGroup(
            jPanelH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanelH1Layout.setVerticalGroup(
            jPanelH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanelHeader.add(jPanelH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 90));

        jPanelH2.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanelH2Layout = new javax.swing.GroupLayout(jPanelH2);
        jPanelH2.setLayout(jPanelH2Layout);
        jPanelH2Layout.setHorizontalGroup(
            jPanelH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanelH2Layout.setVerticalGroup(
            jPanelH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanelHeader.add(jPanelH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 90));

        jPanelH3.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanelH3Layout = new javax.swing.GroupLayout(jPanelH3);
        jPanelH3.setLayout(jPanelH3Layout);
        jPanelH3Layout.setHorizontalGroup(
            jPanelH3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanelH3Layout.setVerticalGroup(
            jPanelH3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanelHeader.add(jPanelH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 90));

        jPanelH4.setBackground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout jPanelH4Layout = new javax.swing.GroupLayout(jPanelH4);
        jPanelH4.setLayout(jPanelH4Layout);
        jPanelH4Layout.setHorizontalGroup(
            jPanelH4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanelH4Layout.setVerticalGroup(
            jPanelH4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanelHeader.add(jPanelH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 90));

        jPanelMenu.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 90));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        jPanelTop.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanelTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTopKiri.setBackground(new java.awt.Color(0, 0, 0, 0));
        jPanelTopKiri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelKiriDesk.setBackground(new java.awt.Color(207, 0, 15, 100));

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel7.setText("Welcome");

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel8.setText("This program still beta version");

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel3.setText("may unstable :)");

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/beta.png"))); // NOI18N

        javax.swing.GroupLayout jpanelKiriDeskLayout = new javax.swing.GroupLayout(jpanelKiriDesk);
        jpanelKiriDesk.setLayout(jpanelKiriDeskLayout);
        jpanelKiriDeskLayout.setHorizontalGroup(
            jpanelKiriDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelKiriDeskLayout.createSequentialGroup()
                .addGroup(jpanelKiriDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelKiriDeskLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jpanelKiriDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanelKiriDeskLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jpanelKiriDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jpanelKiriDeskLayout.setVerticalGroup(
            jpanelKiriDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelKiriDeskLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        jPanelTopKiri.add(jpanelKiriDesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 37, 330, 400));

        jpanelKiriRegister.setBackground(new java.awt.Color(207, 0, 15, 100));
        jpanelKiriRegister.setVisible(false);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel4.setText("Register");

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel5.setText("Usarname");

        txtUsernameReg.setBackground(new java.awt.Color(207, 0, 15));
        txtUsernameReg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        txtPasswordReg.setBackground(new java.awt.Color(207, 0, 15));
        txtPasswordReg.setText("jPasswordField1");
        txtPasswordReg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelRegistered.setBackground(new java.awt.Color(207, 0, 15));
        jPanelRegistered.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegistered.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRegisteredMouseClicked(evt);
            }
        });

        jLabelRegistered.setText("Register");

        javax.swing.GroupLayout jPanelRegisteredLayout = new javax.swing.GroupLayout(jPanelRegistered);
        jPanelRegistered.setLayout(jPanelRegisteredLayout);
        jPanelRegisteredLayout.setHorizontalGroup(
            jPanelRegisteredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
            .addGroup(jPanelRegisteredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRegisteredLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelRegistered)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelRegisteredLayout.setVerticalGroup(
            jPanelRegisteredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(jPanelRegisteredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRegisteredLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelRegistered)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jpanelKiriRegisterLayout = new javax.swing.GroupLayout(jpanelKiriRegister);
        jpanelKiriRegister.setLayout(jpanelKiriRegisterLayout);
        jpanelKiriRegisterLayout.setHorizontalGroup(
            jpanelKiriRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelKiriRegisterLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jpanelKiriRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanelKiriRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUsernameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jpanelKiriRegisterLayout.setVerticalGroup(
            jpanelKiriRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelKiriRegisterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsernameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanelRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPanelTopKiri.add(jpanelKiriRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 38, 330, -1));

        jPanelTop.add(jPanelTopKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        jPanelTopKanan.setBackground(new java.awt.Color(0, 0, 0, 0));

        jLabelButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Close Window_48px.png"))); // NOI18N
        jLabelButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonExitMouseClicked(evt);
            }
        });

        jPanelFormLogin.setBackground(new java.awt.Color(207, 0, 15, 100));
        jPanelFormLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel1.setText("Usarname");
        jPanelFormLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 80, 24));

        txtUsernameLog.setBackground(new java.awt.Color(207, 0, 15));
        txtUsernameLog.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelFormLogin.add(txtUsernameLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 198, 30));

        jPanelLogin.setBackground(new java.awt.Color(207, 0, 15));
        jPanelLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLoginMouseClicked(evt);
            }
        });

        jlabelLogin.setText("Login");

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
            .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                    .addContainerGap(27, Short.MAX_VALUE)
                    .addComponent(jlabelLogin)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                    .addContainerGap(10, Short.MAX_VALUE)
                    .addComponent(jlabelLogin)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        jPanelFormLogin.add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 40));

        jPanelRegister.setBackground(new java.awt.Color(207, 0, 15));
        jPanelRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRegisterMouseClicked(evt);
            }
        });

        jLabelRegister.setText("Register");

        javax.swing.GroupLayout jPanelRegisterLayout = new javax.swing.GroupLayout(jPanelRegister);
        jPanelRegister.setLayout(jPanelRegisterLayout);
        jPanelRegisterLayout.setHorizontalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
            .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelRegister)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelRegisterLayout.setVerticalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelRegister)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelFormLogin.add(jPanelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 90, 40));

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel6.setText("Password");
        jPanelFormLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, 24));

        txtPasswordLog.setBackground(new java.awt.Color(207, 0, 15));
        txtPasswordLog.setText("jPasswordField1");
        txtPasswordLog.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelFormLogin.add(txtPasswordLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 198, 35));

        javax.swing.GroupLayout jPanelTopKananLayout = new javax.swing.GroupLayout(jPanelTopKanan);
        jPanelTopKanan.setLayout(jPanelTopKananLayout);
        jPanelTopKananLayout.setHorizontalGroup(
            jPanelTopKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopKananLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jPanelFormLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelButtonExit)
                .addGap(18, 18, 18))
        );
        jPanelTopKananLayout.setVerticalGroup(
            jPanelTopKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopKananLayout.createSequentialGroup()
                .addGroup(jPanelTopKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTopKananLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanelFormLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTopKananLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelButtonExit)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jPanelTop.add(jPanelTopKanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 430, 480));

        getContentPane().add(jPanelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        jPanelWallpaper.setBackground(new java.awt.Color(0, 0, 0, 0));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/maxresdefault2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelWallpaperLayout = new javax.swing.GroupLayout(jPanelWallpaper);
        jPanelWallpaper.setLayout(jPanelWallpaperLayout);
        jPanelWallpaperLayout.setHorizontalGroup(
            jPanelWallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(jPanelWallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabelWallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWallpaperLayout.setVerticalGroup(
            jPanelWallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
            .addGroup(jPanelWallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabelWallpaper, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelButtonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonExitMouseClicked
        ExitMenu em = new ExitMenu();
        em.setVisible(true);
        jPanelTop.setVisible(false);
    }//GEN-LAST:event_jLabelButtonExitMouseClicked
    
    
    private void jPanelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRegisterMouseClicked
        jpanelKiriDesk.setVisible(false);
        jpanelKiriRegister.setVisible(true);
        setExtendedState(JFrame.ICONIFIED);
        setExtendedState(JFrame.NORMAL);
        
    }//GEN-LAST:event_jPanelRegisterMouseClicked
        
        String usename, pass;
    private void jPanelRegisteredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRegisteredMouseClicked
        usename = txtUsernameReg.getText();
        pass    = txtPasswordReg.getText();
        jpanelKiriDesk.setVisible(true);
        jpanelKiriRegister.setVisible(false);
        setExtendedState(JFrame.ICONIFIED);
        setExtendedState(JFrame.NORMAL);
    }//GEN-LAST:event_jPanelRegisteredMouseClicked

    private void jPanelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLoginMouseClicked
        if ((txtUsernameLog.getText().equals(usename))&&(txtPasswordLog.getText()
                .equals(pass))){
            JOptionPane.showMessageDialog(null, " Login Success");
            jPanelTop.setVisible(false);
            jPanelMenu.setVisible(true);
            setExtendedState(JFrame.ICONIFIED);
            setExtendedState(JFrame.NORMAL);
        
        } else {
            JOptionPane.showMessageDialog(null, " Username or Password is Wrong or Empty");
            setExtendedState(JFrame.ICONIFIED);
            setExtendedState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_jPanelLoginMouseClicked
///////////
    private void jPanel1NavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1NavMouseClicked
        // TODO add your handling code here:
        jPanelH1.setVisible(true);
        jPanelH2.setVisible(false);
        jPanelH3.setVisible(false);
        jPanelH4.setVisible(false);
        
        jpanel1U.setVisible(true);
        jPanel2U.setVisible(false);
        jPanel3U.setVisible(false);
        jPanel4U.setVisible(false);
    }//GEN-LAST:event_jPanel1NavMouseClicked

    private void jPanel2NavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2NavMouseClicked
        // TODO add your handling code here:
        jPanelH1.setVisible(false);
        jPanelH2.setVisible(true);
        jPanelH3.setVisible(false);
        jPanelH4.setVisible(false);
        
        jpanel1U.setVisible(false);
        jPanel2U.setVisible(true);
        jPanel3U.setVisible(false);
        jPanel4U.setVisible(false);
    }//GEN-LAST:event_jPanel2NavMouseClicked

    private void jPanel3NavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3NavMouseClicked
        // TODO add your handling code here:
        jPanelH1.setVisible(false);
        jPanelH2.setVisible(false);
        jPanelH3.setVisible(true);
        jPanelH4.setVisible(false);
        
        jpanel1U.setVisible(false);
        jPanel2U.setVisible(false);
        jPanel3U.setVisible(true);
        jPanel4U.setVisible(false);
    }//GEN-LAST:event_jPanel3NavMouseClicked

    private void jPanel4NavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4NavMouseClicked
        // TODO add your handling code here:
        jPanelH1.setVisible(false);
        jPanelH2.setVisible(false);
        jPanelH3.setVisible(false);
        jPanelH4.setVisible(true);
        
        jpanel1U.setVisible(false);
        jPanel2U.setVisible(false);
        jPanel3U.setVisible(false);
        jPanel4U.setVisible(true);
    }//GEN-LAST:event_jPanel4NavMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        jPanelMenu.setVisible(false);
        jPanelTop.setVisible(true);
        jPanelWallpaper.setVisible(true);
        setExtendedState(JFrame.ICONIFIED);
        setExtendedState(JFrame.NORMAL);
        
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelButtonExit;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabelRegistered;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JPanel jPanel1Nav;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2Nav;
    private javax.swing.JPanel jPanel2U;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel3Nav;
    private javax.swing.JPanel jPanel3U;
    private javax.swing.JPanel jPanel4Nav;
    private javax.swing.JPanel jPanel4U;
    private javax.swing.JPanel jPanelFormLogin;
    private javax.swing.JPanel jPanelH1;
    private javax.swing.JPanel jPanelH2;
    private javax.swing.JPanel jPanelH3;
    private javax.swing.JPanel jPanelH4;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelMenuU;
    private javax.swing.JPanel jPanelNav;
    private javax.swing.JPanel jPanelRegister;
    private javax.swing.JPanel jPanelRegistered;
    public static javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanelTopKanan;
    private javax.swing.JPanel jPanelTopKiri;
    private javax.swing.JPanel jPanelWallpaper;
    private javax.swing.JLabel jlabelLogin;
    private javax.swing.JPanel jpanel1U;
    private javax.swing.JPanel jpanelKiriDesk;
    private javax.swing.JPanel jpanelKiriRegister;
    private javax.swing.JPanel jpanelLogutNav;
    private javax.swing.JPasswordField txtPasswordLog;
    private javax.swing.JPasswordField txtPasswordReg;
    private javax.swing.JTextField txtUsernameLog;
    private javax.swing.JTextField txtUsernameReg;
    // End of variables declaration//GEN-END:variables
}
